version: '3.8'
services:
  postgresql:
    build: docker/postgresql
    volumes:
      - postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shelter
    ports:
      - "5433:5432"

volumes:
  postgresql: