export * from './fakturyController.service';
import { FakturyControllerService } from './fakturyController.service';
export * from './gatunekController.service';
import { GatunekControllerService } from './gatunekController.service';
export * from './lecznicaController.service';
import { LecznicaControllerService } from './lecznicaController.service';
export * from './ludzieController.service';
import { LudzieControllerService } from './ludzieController.service';
export * from './pracownicyController.service';
import { PracownicyControllerService } from './pracownicyController.service';
export * from './zbiorkiController.service';
import { ZbiorkiControllerService } from './zbiorkiController.service';
export * from './zwierzetaController.service';
import { ZwierzetaControllerService } from './zwierzetaController.service';
export const APIS = [FakturyControllerService, GatunekControllerService, LecznicaControllerService, LudzieControllerService, PracownicyControllerService, ZbiorkiControllerService, ZwierzetaControllerService];
